export enum ServiceNames {
  ORDER_SERVICE = 'ORDER_SERVICE',
  PRODUCT_SERVICE = 'PRODUCT_SERVICE',
  PAYMENT_SERVICE = 'PAYMENT_SERVICE',
  SHIPPING_SERVICE = 'SHIPPING_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
};